;; 文字コード
;; note: win, mac, linux で環境を分けている
(set-language-environment "Japanese")
(let ((ws window-system))
  (cond ((eq ws 'w64)
         (prefer-coding-system 'utf-8-unix)
         (set-default-coding-systems 'utf-8-unix)
         (setq file-name-coding-system 'sjis)
         (setq locale-coding-system 'utf-8))
        ((eq ws 'ns)
         (require 'ucs-normalize)
         (prefer-coding-system 'utf-8-hfs)
         (setq file-name-coding-system 'utf-8-hfs)
         (setq locale-coding-system 'utf-8-hfs))
        ((eq ws 'x)
         (set-terminal-coding-system 'utf-8-unix)
         (setq file-name-coding-system 'utf-8-unix)
         (set-clipboard-coding-system 'utf-8-unix)
         (setq default-buffer-file-coding-system 'utf-8-unix)
         (prefer-coding-system 'utf-8-unix)
         (set-default-coding-systems 'utf-8-unix)
         (set-keyboard-coding-system 'utf-8-unix)
         (set-buffer-file-coding-system 'utf-8-unix))))
