# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zsh を emacs キーバインドで使う
bindkey -e

alias vim=nvim
alias ls='ls --color=always'
alias code='code-insiders'

# Homebrew の PATH 追加
export PATH=/opt/homebrew/bin:$PATH

# 補完の有効化
autoload -U compinit && compinit

# zplug
export ZPLUG_HOME=/opt/homebrew/opt/zplug
source $ZPLUG_HOME/init.zsh

# gh コマンドのエディタを vim に変更
export EDITOR=vim

# zplug plugin
## テーマ
zplug "romkatv/powerlevel10k", as:theme, depth:1

## シンタックスハイライト
zplug "zsh-users/zsh-syntax-highlighting"
zplug "chrissicool/zsh-256color"

zplug load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# functions
## ssh の接続先を fzf で選択
## https://qiita.com/kamykn/items/9a831862038efa4e9f8f
fssh() {
    local sshLoginHost
    sshLoginHost=`cat ~/.ssh/config | grep -i ^host | awk '{print $2}' | fzf`

    if [ "$sshLoginHost" = "" ]; then
        # ex) Ctrl-C.
        return 1
    fi

    ssh ${sshLoginHost}
}

